### PR TITLE
Added object tracking support.

### PR DESCRIPTION
**Pull request by bre80**
Added opencv submodule
Fixed bug with detecting when WASM module finishes loading.

### CODE REVIEW

**Review by jordanaustin — APPROVED** [review]
LGTM, but I'm not the expert here

**Review by minorgal — APPROVED** [review]
LGTM - @joeybladb should probably take a look over it.

Nice Job getting this done

**Comment by bre80** [comment]
Thanks.  I'll get Joe on it.  I wasn't sure what his username was.

**Review by stocktonkincade — APPROVED** [review]

**Comment by joeybladb** [comment]
I approve this.

**Pull request merged**
